# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnalyzeCosts(object):
    def setupUi(self, AnalyzeCosts):
        AnalyzeCosts.setObjectName("AnalyzeCosts")
        AnalyzeCosts.resize(614, 477)
        self.centralwidget = QtWidgets.QWidget(AnalyzeCosts)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plan_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plan_label.sizePolicy().hasHeightForWidth())
        self.plan_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plan_label.setFont(font)
        self.plan_label.setObjectName("plan_label")
        self.verticalLayout_2.addWidget(self.plan_label)
        self.plan_list = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plan_list.sizePolicy().hasHeightForWidth())
        self.plan_list.setSizePolicy(sizePolicy)
        self.plan_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.plan_list.setObjectName("plan_list")
        self.verticalLayout_2.addWidget(self.plan_list)
        self.label_ref_plan = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ref_plan.sizePolicy().hasHeightForWidth())
        self.label_ref_plan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ref_plan.setFont(font)
        self.label_ref_plan.setObjectName("label_ref_plan")
        self.verticalLayout_2.addWidget(self.label_ref_plan)
        self.comboBox_refplan = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_refplan.sizePolicy().hasHeightForWidth())
        self.comboBox_refplan.setSizePolicy(sizePolicy)
        self.comboBox_refplan.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.comboBox_refplan.setObjectName("comboBox_refplan")
        self.verticalLayout_2.addWidget(self.comboBox_refplan)
        self.label_uncert = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_uncert.sizePolicy().hasHeightForWidth())
        self.label_uncert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_uncert.setFont(font)
        self.label_uncert.setObjectName("label_uncert")
        self.verticalLayout_2.addWidget(self.label_uncert)
        self.spinBox_uncert = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_uncert.sizePolicy().hasHeightForWidth())
        self.spinBox_uncert.setSizePolicy(sizePolicy)
        self.spinBox_uncert.setProperty("value", 5)
        self.spinBox_uncert.setObjectName("spinBox_uncert")
        self.verticalLayout_2.addWidget(self.spinBox_uncert)
        self.progressBar_plotting = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_plotting.sizePolicy().hasHeightForWidth())
        self.progressBar_plotting.setSizePolicy(sizePolicy)
        self.progressBar_plotting.setProperty("value", 0)
        self.progressBar_plotting.setObjectName("progressBar_plotting")
        self.verticalLayout_2.addWidget(self.progressBar_plotting)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.checkBox_organUpdate = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_organUpdate.setFont(font)
        self.checkBox_organUpdate.setObjectName("checkBox_organUpdate")
        self.verticalLayout_2.addWidget(self.checkBox_organUpdate)
        self.pushButton_gt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_gt.sizePolicy().hasHeightForWidth())
        self.pushButton_gt.setSizePolicy(sizePolicy)
        self.pushButton_gt.setObjectName("pushButton_gt")
        self.verticalLayout_2.addWidget(self.pushButton_gt)
        self.pushButton_gc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_gc.setObjectName("pushButton_gc")
        self.verticalLayout_2.addWidget(self.pushButton_gc)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_2.addWidget(self.pushButton_save)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.plot_layout = QtWidgets.QGridLayout()
        self.plot_layout.setObjectName("plot_layout")
        self.widget_HbarSummary = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_HbarSummary.sizePolicy().hasHeightForWidth())
        self.widget_HbarSummary.setSizePolicy(sizePolicy)
        self.widget_HbarSummary.setObjectName("widget_HbarSummary")
        self.HbarSummary = QtWidgets.QVBoxLayout(self.widget_HbarSummary)
        self.HbarSummary.setContentsMargins(0, 0, 0, 0)
        self.HbarSummary.setObjectName("HbarSummary")
        self.plot_layout.addWidget(self.widget_HbarSummary, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_organ1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_organ1.sizePolicy().hasHeightForWidth())
        self.label_organ1.setSizePolicy(sizePolicy)
        self.label_organ1.setObjectName("label_organ1")
        self.verticalLayout.addWidget(self.label_organ1)
        self.comboBox_organ1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_organ1.setObjectName("comboBox_organ1")
        self.verticalLayout.addWidget(self.comboBox_organ1)
        self.widget_organ1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_organ1.setObjectName("widget_organ1")
        self.organ1 = QtWidgets.QHBoxLayout(self.widget_organ1)
        self.organ1.setContentsMargins(0, 0, 0, 0)
        self.organ1.setObjectName("organ1")
        self.verticalLayout.addWidget(self.widget_organ1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_organ2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_organ2.sizePolicy().hasHeightForWidth())
        self.label_organ2.setSizePolicy(sizePolicy)
        self.label_organ2.setObjectName("label_organ2")
        self.verticalLayout_5.addWidget(self.label_organ2)
        self.comboBox_organ2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_organ2.setObjectName("comboBox_organ2")
        self.verticalLayout_5.addWidget(self.comboBox_organ2)
        self.widget_organ2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_organ2.setObjectName("widget_organ2")
        self.organ2 = QtWidgets.QHBoxLayout(self.widget_organ2)
        self.organ2.setContentsMargins(0, 0, 0, 0)
        self.organ2.setObjectName("organ2")
        self.verticalLayout_5.addWidget(self.widget_organ2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_organ3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_organ3.sizePolicy().hasHeightForWidth())
        self.label_organ3.setSizePolicy(sizePolicy)
        self.label_organ3.setObjectName("label_organ3")
        self.verticalLayout_6.addWidget(self.label_organ3)
        self.comboBox_organ3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_organ3.setObjectName("comboBox_organ3")
        self.verticalLayout_6.addWidget(self.comboBox_organ3)
        self.widget_organ3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_organ3.sizePolicy().hasHeightForWidth())
        self.widget_organ3.setSizePolicy(sizePolicy)
        self.widget_organ3.setObjectName("widget_organ3")
        self.organ3 = QtWidgets.QHBoxLayout(self.widget_organ3)
        self.organ3.setContentsMargins(0, 0, 0, 0)
        self.organ3.setObjectName("organ3")
        self.verticalLayout_6.addWidget(self.widget_organ3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.plot_layout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plot_layout.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.widget_gtTracks = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_gtTracks.sizePolicy().hasHeightForWidth())
        self.widget_gtTracks.setSizePolicy(sizePolicy)
        self.widget_gtTracks.setObjectName("widget_gtTracks")
        self.gtTracks = QtWidgets.QHBoxLayout(self.widget_gtTracks)
        self.gtTracks.setContentsMargins(0, 0, 0, 0)
        self.gtTracks.setObjectName("gtTracks")
        self.plot_layout.addWidget(self.widget_gtTracks, 2, 0, 1, 1)
        self.widget_gcTracks = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_gcTracks.sizePolicy().hasHeightForWidth())
        self.widget_gcTracks.setSizePolicy(sizePolicy)
        self.widget_gcTracks.setObjectName("widget_gcTracks")
        self.gcTracks = QtWidgets.QHBoxLayout(self.widget_gcTracks)
        self.gcTracks.setContentsMargins(0, 0, 0, 0)
        self.gcTracks.setObjectName("gcTracks")
        self.plot_layout.addWidget(self.widget_gcTracks, 3, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.plot_layout)
        AnalyzeCosts.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnalyzeCosts)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 25))
        self.menubar.setObjectName("menubar")
        AnalyzeCosts.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(AnalyzeCosts)
        self.statusBar.setObjectName("statusBar")
        AnalyzeCosts.setStatusBar(self.statusBar)

        self.retranslateUi(AnalyzeCosts)
        self.comboBox_refplan.setCurrentIndex(-1)
        self.comboBox_organ1.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AnalyzeCosts)

    def retranslateUi(self, AnalyzeCosts):
        _translate = QtCore.QCoreApplication.translate
        AnalyzeCosts.setWindowTitle(_translate("AnalyzeCosts", "MainWindow"))
        self.plan_label.setText(_translate("AnalyzeCosts", "plans:"))
        self.label_ref_plan.setText(_translate("AnalyzeCosts", "reference plan:"))
        self.label_uncert.setText(_translate("AnalyzeCosts", "uncertainty [%] :"))
        self.checkBox_organUpdate.setText(_translate("AnalyzeCosts", "Live Organ Update "))
        self.pushButton_gt.setText(_translate("AnalyzeCosts", "plot gt"))
        self.pushButton_gc.setText(_translate("AnalyzeCosts", "plot gc"))
        self.pushButton_save.setText(_translate("AnalyzeCosts", "SAVE"))
        self.label_organ1.setText(_translate("AnalyzeCosts", "organ1:"))
        self.label_organ2.setText(_translate("AnalyzeCosts", "organ2:"))
        self.label_organ3.setText(_translate("AnalyzeCosts", "organ3:"))

